# ********** fbank features here are extracted using ESPnet make_fbank.sh with
# stft's center=False (that correspondings to --snip-edges=true in kaldi
# version) ********* BUT will use grifinlim with ceneter=True. This
# inconsistency did not give any problem in one sample experiment

# (Just to note) Output from "$ls -F" before running anything in this dir
cmd.sh           list_run.sh  path.sh     run.debug.sh*          run.sh*            run.ttsspkid.sh*  steps@                     utils@
environment.yml  local/       RESULTS.md  run.FE.diffconfig.libritts.sh*  run.tts+spkid.sh*  sid@              update_json.spkid.temp.sh

# Run ESPnet make_fbank.sh: I will run one by one from the beginning
mkdir log

##
bash run.FE.diffconfig.libritts.sh --stage -1 --stop_stage -1 --datadir /export/a15/jcho/data 2>&1 | tee log/run.FE.diffconfig.datadir.stage_1.log
### what's generated (dump/ and exp/ directories are generated. Just the structure w/o any contents)
drwxr-xr-x 5 jcho fax    77 Apr  7 14:15 dump
drwxr-xr-x 3 jcho fax    75 Apr  7 14:15 exp
$ls dump/*
dump/dev_clean:

dump/test_clean:

dump/train_clean_460:
$ls exp/*
###

##
bash run.FE.diffconfig.libritts.sh --stage 0 --stop_stage 0 --datadir /export/a15/jcho/data 2>&1 | tee log/run.FE.diffconfig.datadir.stage0.log
### what's genearted (spk2gender  spk2utt  text  utt2spk  wav.scp are generated in each data directory)
### generated files have no difference compared to ../tts1/data/* except some utts are filtered out in dev_clean I think by files that didn't generate any features
drwxr-xr-x 2 jcho fax    77 Apr  7 15:31 data
$ls data/*
data/dev_clean:
spk2gender  spk2utt  text  utt2spk  wav.scp

data/test_clean:
spk2gender  spk2utt  text  utt2spk  wav.scp

data/train_clean_100:
spk2gender  spk2utt  text  utt2spk  wav.scp

data/train_clean_360:
spk2gender  spk2utt  text  utt2spk  wav.scp
###

##
bash run.FE.diffconfig.libritts.sh --stage 1 --stop_stage 1 2>&1 | tee log/run.FE.diffconfig.stage1.log # feature generation with n_shift 240
### what's generated (files regarding feature generation are added)
drwxr-xr-x 2 jcho fax 24576 Apr  7 15:55 fbank
drwxr-xr-x 9 jcho fax  4096 Apr  7 16:06 data
drwxr-xr-x 5 jcho fax   117 Apr  7 16:09 exp
$ls fbank # newly generated directory from this stage
... # too many files
$ls data # some files are added from the previous stage (stage 0)
data/dev_clean:
feats.scp  filetype  spk2gender  spk2utt  text  tmp  utt2num_frames  utt2spk  wav.scp

data/dev_clean_org:
feats.scp  log  spk2gender  spk2utt  split4utt  text  utt2num_frames  utt2spk  wav.scp

data/test_clean:
feats.scp  filetype  spk2gender  spk2utt  text  utt2num_frames  utt2spk  wav.scp

data/train_clean_100:
feats.scp  filetype  spk2gender  spk2utt  text  utt2num_frames  utt2spk  wav.scp

data/train_clean_360:
feats.scp  filetype  spk2gender  spk2utt  text  utt2num_frames  utt2spk  wav.scp

data/train_clean_460:
cmvn.ark  feats.scp  spk2gender  spk2utt  text  tmp  utt2num_frames  utt2spk  wav.scp

data/train_clean_460_org:
feats.scp  log  spk2gender  spk2utt  split4utt  text  utt2num_frames  utt2spk  wav.scp
$ls exp # some files are generated to the previously empty exp/
exp/dump_feats:
dev  eval  train

exp/make_fbank:
dev_clean  test_clean  train_clean_100  train_clean_360

exp/train_clean_460_pytorch_train_pytorch_tacotron2+spkemb:
###

## In the end, I've rerun all of the above lines with one line as below after removing all the outputs generated by the above lines
bash run.FE.diffconfig.libritts.sh --stage -1 --stop_stage 1 --datadir /export/a15/jcho/data 2>&1 | tee log/run.FE.diffconfig.datadir.fromstage_1to1.log

## (Sanity check) I compared the generated files so far to files in ../tts1/
## All looks good in tmp.diff
for dirname in `ls data/`;do
    echo dirname: data/${dirname}
    for fname in `ls data/${dirname}/`;do
        tmpname=data/${dirname}/${fname}
        echo fname: ${tmpname}
        diff ${tmpname} ../tts1/${tmpname} | wc -l
    done
done > tmp.diff

## Get some files from ../tts+spkid_final/data/train_clean_460/
cp /export/b18/jcho/espnet3/egs/libritts/tts+spkid_final/data/train_clean_460/train_{train,dev,eval}.uttlist data/train_clean_460/
cp /export/b18/jcho/espnet3/egs/libritts/tts+spkid_final/data/train_clean_460/train_trainNdev.{utt2spklab,utt2spklab_NOspk2085} data/train_clean_460/


