# Copy subsets from /export/b13/jcho/espnet_v3/tools/kaldi/egs/voxceleb/v2
oridir=/export/b13/jcho/espnet_v3/tools/kaldi/egs/voxceleb/v2
cp -r ${oridir}/data/voxceleb2_2400spk data/
cp -r ${oridir}/data/voxceleb2_1600spk data/
cp -r ${oridir}/data/voxceleb2_800spk data/

# Compose feats.scp
. path.sh
orifeat=data/voxceleb_train/feats.scp # voxceleb_train is generated by removing long utterances from voxceleb_train_org
filter_scp.pl <(awk '{print $1}' data/voxceleb2_2400spk/utt2spk) ${orifeat} > data/voxceleb2_2400spk/feats.scp
fix_data_dir.sh data/voxceleb2_2400spk
filter_scp.pl <(awk '{print $1}' data/voxceleb2_1600spk/utt2spk) ${orifeat} > data/voxceleb2_1600spk/feats.scp
fix_data_dir.sh data/voxceleb2_1600spk
filter_scp.pl <(awk '{print $1}' data/voxceleb2_800spk/utt2spk) ${orifeat} > data/voxceleb2_800spk/feats.scp
fix_data_dir.sh data/voxceleb2_800spk
