# (ING) I am checking this script one by one. (Original parts are being copied one by one from the stage 2 of run.FE.diffconfig.voxceleb_kaldiprep.sh)

. ./path.sh || exit 1;
. ./cmd.sh || exit 1;

# general configuration
stage=-1
stop_stage=100

# feature extraction related
fs=8000      # sampling frequency
fmax=""       # maximum frequency
fmin=""       # minimum frequency
n_fft=256    # number of fft points (~32ms) ***** JJ: maybe this leads to a poor result? (tacotron2 paper: 50ms, previous run.sh ~42ms)
n_shift=80   # number of shift points (~10ms)
win_length="" # window length
n_mels=64     # number of mel basis



. utils/parse_options.sh || exit 1;

# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

#kaldi_datadir=/export/b16/jcho/hyperion_trials/egs/sre20-cts/v1/data
#dataname=sre16_eval_tr60_yue
#mkdir -p data/${train_set}
#cp ${kaldi_datadir}/${dataname}/{wav.scp,utt2spk,spk2utt,utt2num_frames} data/${train_set}
train_set=rir_check # this directory is just to check if this whole script runs correctly (generated by the block of lines right above). (TODO: once this is done "train_set" will be something like [ori corpus name]_prepared_by_hyperion. & "train_set_saded" will be processed data dir til sad (and then FE))

# In this section, we augment the VoxCeleb2 data with reverberation,
# noise, music, and babble, and combine it with the clean data.
if [ ${stage} -le 2 ] && [ ${stop_stage} -ge 2 ]; then
  echo "stage 2: Data augmentation"
  calc(){ awk "BEGIN { print "$*" }"; }
  frame_shift=`calc ${n_shift}/${fs}`
  echo "Calculated frame shift: ${frame_shift} sec"

  awk -v frame_shift=$frame_shift '{print $1, $2*frame_shift;}' data/${train_set}/utt2num_frames > data/${train_set}/reco2dur

  if [ ! -d "RIRS_NOISES" ]; then
    # Download the package that includes the real RIRs, simulated RIRs, isotropic noises and point-source noises
    wget --no-check-certificate http://www.openslr.org/resources/28/rirs_noises.zip
    unzip rirs_noises.zip
  fi

  # Make a version with reverberated speech
  rvb_opts=()
  rvb_opts+=(--rir-set-parameters "0.5, RIRS_NOISES/simulated_rirs/smallroom/rir_list")
  rvb_opts+=(--rir-set-parameters "0.5, RIRS_NOISES/simulated_rirs/mediumroom/rir_list")

  # Make a reverberated version of the VoxCeleb2 list.  Note that we don't add any
  # additive noise here.
  steps/data/reverberate_data_dir.py \
    "${rvb_opts[@]}" \
    --speech-rvb-probability 1 \
    --pointsource-noise-addition-probability 0 \
    --isotropic-noise-addition-probability 0 \
    --num-replications 1 \
    --source-sampling-rate ${fs} \
    data/${train_set} data/${train_set}_reverb
  utils/copy_data_dir.sh --utt-suffix "-reverb" data/${train_set}_reverb data/${train_set}_reverb.new # (TODO: before this line, copy from "NO-aug processed data dir" all others including segments)
  rm -rf data/${train_set}_reverb
  mv data/${train_set}_reverb.new data/${train_set}_reverb

  # Prepare the MUSAN corpus, which consists of music, speech, and noise
  # suitable for augmentation.
  if [ ! -f local/make_musan.sh ]; then
      kaldi_voxceleb_dir=/export/b13/jcho/espnet_v3/tools/kaldi/egs/voxceleb/v2/
      cp ${kaldi_voxceleb_dir}/local/make_musan.sh local/
      cp ${kaldi_voxceleb_dir}/local/make_musan.py local/

  fi
  local/make_musan.sh $musan_root data

  # Get the duration of the MUSAN recordings.  This will be used by the
  # script augment_data_dir.py.
  for name in speech noise music; do
    if [ ! -s data/musan_${name}/reco2dur ]; then
        utils/data/get_utt2dur.sh data/musan_${name}
        mv data/musan_${name}/utt2dur data/musan_${name}/reco2dur
    fi
  done

# Augment with musan_noise # (TODO: Like the TODO above for reverb, I need to copy from "NO-aug processed data dir" all others including segments)
# Before this stage, I ran "grep -Rl "/export/corpora/" data/musan* | xargs sed -i 's!/export/corpora/!/export/corpora5/!g' # reference: https://naysan.ca/2020/06/02/linux-command-line-find-replace-in-multiple-files/" since /export/corpora/ now is /export/corpora5/
  #steps/data/augment_data_dir.py --utt-suffix "noise" --fg-interval 1 --fg-snrs "15:10:5:0" --fg-noise-dir "data/musan_noise" data/${train_set} data/${train_set}_noise
  steps/data/augment_data_dir.py --utt-suffix "suffix2bremoved" --fg-interval 1 --fg-snrs "15:10:5:0" --fg-noise-dir "data/musan_noise" data/${train_set} data/${train_set}_noise
  grep -Rl "suffix2bremoved" data/${train_set}_noise | xargs sed -i 's/-suffix2bremoved//g' # By this line, only difference in files bewteen data/${train_set} and data/${train_set}_noise is wav.scp contents
  cp data/${train_set_saded}/{segments,spk2utt,utt2spk} data/${train_set}_noise
  utils/copy_data_dir.sh --utt-suffix "-noise" data/${train_set}_noise data/${train_set}_noise.new # (TODO: before this line, copy from "NO-aug processed data dir" all others including segments)
  rm -rf data/${train_set}_noise
  mv data/${train_set}_noise.new data/${train_set}_noise
#  # Augment with musan_music
#  steps/data/augment_data_dir.py --utt-suffix "music" --bg-snrs "15:10:8:5" --num-bg-noises "1" --bg-noise-dir "data/musan_music" data/${train_set} data/${train_set}_music
#  # Augment with musan_speech
#  steps/data/augment_data_dir.py --utt-suffix "babble" --bg-snrs "20:17:15:13" --num-bg-noises "3:4:5:6:7" --bg-noise-dir "data/musan_speech" data/${train_set} data/${train_set}_babble
#
#  # Combine reverb, noise, music, and babble into one directory.
#  utils/combine_data.sh data/${train_set}_aug data/${train_set}_reverb data/${train_set}_noise data/${train_set}_music data/${train_set}_babble
fi
