# This is the basic tactron2 training settting

model-module: espnet.nets.pytorch_backend.e2e_tts_tacotron2_speakerid_update_fullyunsync_nce_specaug:Tacotron2

# encoder related
embed-dim: 512
elayers: 1
eunits: 512
econv-layers: 3 # if set 0, no conv layer is used
econv-chans: 512
econv-filts: 5

# decoder related
dlayers: 2
dunits: 1024
prenet-layers: 2  # if set 0, no prenet is used
prenet-units: 256
postnet-layers: 5 # if set 0, no postnet is used
postnet-chans: 512
postnet-filts: 5
use-speaker-embedding: true

# attention related
num-save-attention: 0 # no attention
atype: noatt # no attention
adim: 128
aconv-chans: 32
aconv-filts: 15      # resulting in filter-size = aconv-filts * 2 + 1
cumulate-att-w: true # whether to cumulate attetion weight
use-batch-norm: true # whether to use batch normalization in conv layer
use-concate: true    # whether to concatenate encoder embedding with decoder lstm outputs
use-residual: false  # whether to use residual connection in encoder convolution
use-masking: true    # whether to mask the padded part in loss calculation
bce-pos-weight: 1.0  # weight for positive samples of stop token in cross-entropy calculation
reduction-factor: 3  # due to no attention, # decoder output frames == (approx.) 3 x # input frames

# minibatch related
batch-size: 64         # (memory erro) from 192 to 128 to 100 to 64
batch-sort-key: output # shuffle or input or output
maxlen-in: 133         # if input length  > maxlen-in, batchsize is reduced (if use "shuffle", not effect). For atype='noatt', it is same as maxlen-out since 3 x # input frames == (approx.) # output frames
maxlen-out: 400        # if output length > maxlen-out, batchsize is reduced (if use "shuffle", not effect)

# optimization related
lr: 1e-3
eps: 1e-6
weight-decay: 0.0
dropout-rate: 0.5
zoneout-rate: 0.1
epochs: 30
patience: 0
